# -*- coding: utf-8 -*-
{
    'name': '云片短信模块',
    'summary': u'Tools',
    'category': u'Tools',
    'sequence': 90,
    'author': 'melon',
    'website': 'https://www.hxmelon.com',
    'depends': ['base'],
    "license": "LGPL-3",
    'currency': "USD",
    'price': 0.88,
    'version': '15.0.1',
    "images": ["static/description/img_2.png"],
    'data': [
        'data/ir_config_parameter_data.xml',
        'data/ir_sequence_data.xml',
        'security/ir.model.access.csv',
        'views/hd_send_sms_views.xml',
        'views/hd_sms_order_views.xml',
        'views/hd_sms_templates_views.xml',
        'views/action_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'description': u"""云片短息发送模块""",
}
